= Setup
include::_attributes.adoc[]

[#prerequisite]
== Prerequisite CLI tools

You will need in this tutorial:
* openshift
** Mac: `brew install openshift-cli`
* `minishift` 
** https://github.com/minishift/minishift/releases[Mac OS and Fedora]
* docker
** https://www.docker.com/docker-mac[Mac OS]
** Fedora: `dnf install docker`
* kubectl
** https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl-binary-via-curl[Mac OS]
** Fedora: `dnf install kubernetes-client`
* `oc (eval $(minishift oc-env))`
* Apache Maven
** https://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz[Mac OS]
** Fedora: `dnf install maven`
* link:https://github.com/wercker/stern[stern]
** Mac OS: `brew install stern`
** Fedora: `sudo curl --output /usr/local/bin/stern -L https://github.com/wercker/stern/releases/download/1.6.0/stern_linux_amd64 && sudo chmod +x /usr/local/bin/stern`
* istioctl (will be installed via the steps below)
* `curl`, `gunzip`, `tar` 
** Mac OS: built-in or part of your bash shell
** Fedora: should also be installed already, but just in case... `dnf install curl gzip tar`
* git
** `dnf install git`

[#minishift]
== Setup minishift

Assumes `minishift`, tested with minishift v1.25.0+90fb23e

[source,bash]
----
#!/bin/bash

# add the location of minishift executable to PATH
# I also keep other handy tools like kubectl and kubetail.sh
# in that directory

minishift profile set istio-tutorial
minishift config set memory 8GB
minishift config set cpus 3
minishift config set vm-driver virtualbox ## or kvm, for Fedora
minishift config set image-caching true
minishift addon enable admin-user
minishift addon enable anyuid

minishift start

# Configuration for Elastic Search
minishift ssh -- "echo "vm.max_map_count = 262144" | sudo tee --append /etc/sysctl.d/99-elasticsearch.conf"
minishift ssh -- sudo sysctl vm.max_map_count=262144
----

[#environment]
== Setup environment

[source,bash]
----
eval $(minishift oc-env)
eval $(minishift docker-env)
oc login $(minishift ip):8443 -u admin -p admin
----

NOTE: In this tutorial, you will often be polling the customer endpoint with `curl`, while simultaneously viewing logs via `stern` or `kubetail.sh` and issuing commands via `oc` and `istioctl`. Consider using three terminal windows.

[#istioinstallation]
== Istio installation script

[source,bash]
----
#!/bin/bash

# Mac OS:
curl -L https://github.com/istio/istio/releases/download/1.0.2/istio-1.0.2-osx.tar.gz | tar xz

# Fedora/RHEL:
curl -L https://github.com/istio/istio/releases/download/1.0.2/istio-1.0.2-linux.tar.gz | tar xz

# Both:
cd istio-1.0.2
export ISTIO_HOME=`pwd`
export PATH=$ISTIO_HOME/bin:$PATH

----

[source,bash]
----
oc new-project istio-operator

oc new-app -f  https://raw.githubusercontent.com/Maistra/openshift-ansible/maistra-0.2.0-ocp-3.1.0-istio-1.0.2/istio/istio_community_operator_template.yaml --param=OPENSHIFT_ISTIO_MASTER_PUBLIC_URL=$(minishift console --url)

oc create -f https://raw.githubusercontent.com/Maistra/openshift-ansible/maistra-0.2.0-ocp-3.1.0-istio-1.0.2/istio/cr-minimal.yaml -n istio-operator

----

Wait for Istio's components to be ready. It should take approximetely 5 to 10 minutes to complete.

[source,bash]
----
$ oc get pods -w -n istio-system
or
$ kubectl get pods -w

NAME                                          READY     STATUS              RESTARTS   AGE
elasticsearch-0                               0/1       ContainerCreating   0          21s
grafana-65db6b47c9-kmtk7                      1/1       Running             0          31s
istio-citadel-65f58755d-j6wwp                 1/1       Running             0          1m
istio-egressgateway-79d76795d5-npbgc          1/1       Running             0          1m
istio-galley-644dfdb95-kq4t4                  1/1       Running             0          1m
istio-ingressgateway-5599cdfc7d-t8xk9         1/1       Running             0          1m
istio-pilot-69f89947b8-8h25n                  2/2       Running             0          1m
istio-policy-764d95895d-n5766                 2/2       Running             0          1m
istio-sidecar-injector-649b9c98d9-kwcd8       1/1       Running             0          1m
istio-statsd-prom-bridge-7f44bb5ddb-77xkw     1/1       Running             0          1m
istio-telemetry-58f5d5895-nf7bj               2/2       Running             0          1m
openshift-ansible-istio-installer-job-mqhrr   1/1       Running             0          3m
prometheus-84bd4b9796-hrshh                   1/1       Running             0          1m
----

And if you need quick access to the OpenShift console

[source,bash]
----
minishift console
----

NOTE: On your first launch of the OpenShift console via `minishift`, you will receive a warning like "Your connection is not private". For our demo, simply select "Proceed to 192.168.xx.xx (unsafe)" to bypass the warning. Both the username and the password are set to `admin`, thanks to the `admin-user` add-on.
