= Setup
include::_attributes.adoc[]

[#prerequisite]
== Prerequisite CLI tools

You will need in this tutorial:

* `virtualbox`
** https://www.virtualbox.org/wiki/Downloads[MacOS, Windows and Linux]
* `minikube`
** https://kubernetes.io/docs/tasks/tools/install-minikube/[MacOS, Windows and Fedora]
* docker
** https://www.docker.com/docker-mac[MacOS]
** Fedora: `dnf install docker`
* kubectl
** https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl-binary-via-curl[MacOS, Windows and Fedora]
** Fedora: `dnf install kubernetes-client`
* Apache Maven
** https://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz[MacOS, Windows and Linux]
** Fedora: `dnf install maven`
* link:https://github.com/wercker/stern[stern]
** Mac OS: `brew install stern`
** Fedora: `sudo curl --output /usr/local/bin/stern -L https://github.com/wercker/stern/releases/download/1.6.0/stern_linux_amd64 && sudo chmod +x /usr/local/bin/stern`
* istioctl (will be installed via the steps below)
* `curl`, `gunzip`, `tar`
** Mac OS: built-in or part of your bash shell
** Fedora: should also be installed already, but just in case... `dnf install curl gzip tar`
* git
** `dnf install git`
* siege
** MAC OS: `brew install siege`
** Fedora: `dnf install siege`


[TIP]
====
If you want to validate if everything is installed at once, just open a terminal and run:

`curl -sL https://git.io/_has | HAS_ALLOW_UNSAFE=y bash -s`

The output should be something like:

[source, bash]
----
✔ minikube
✔ docker 18.09.0
✔ kubectl
✔ git 2.17.2
✔ mvn 3.5.0
✔ curl 7.54.0
✔ stern 1.6.0
✔ siege 4.0.4
----

You can check quickly if you are missing any tool and decide if you want to install or not.
====

[#minikube]
== Setup minikube

In case of using Minikube you need at least minikube v1.7.4.

[source,bash,subs="+macros,+attributes"]
----
minikube start --memory=8192 --cpus=3 --kubernetes-version=v1.17.4 --vm-driver=virtualbox -p istio
----

[#environment]
== Setup environment

[source,bash,subs="+macros,+attributes"]
----
eval $(minikube docker-env -p istio)
----

NOTE: In this tutorial, you will often be polling the customer endpoint with `curl`, while simultaneously viewing logs via `stern` or `kubetail.sh` and issuing commands via `kubectl` and `istioctl`. Consider using three terminal windows.

[#upstreamistioinstallation]
== Upstream Istio installation

[source,bash,subs="+macros,+attributes"]
----
#!/bin/bash

# Mac OS:
curl -L https://github.com/istio/istio/releases/download/{istio-version}/istio-{istio-version}-osx.tar.gz | tar xz

# Fedora/RHEL:
curl -L https://github.com/istio/istio/releases/download/{istio-version}/istio-{istio-version}-linux.tar.gz | tar xz

# Both:
cd istio-{istio-version}
export ISTIO_HOME=`pwd`
export PATH=$ISTIO_HOME/bin:$PATH

----

[source,bash,subs="+macros,+attributes"]
----

istioctl manifest apply --set profile=demo
- Applying manifest for component Base...
✔ Finished applying manifest for component Base.
- Applying manifest for component Tracing...
- Applying manifest for component Kiali...
- Applying manifest for component IngressGateway...
- Applying manifest for component Pilot...
- Applying manifest for component Galley...
- Applying manifest for component EgressGateway...
- Applying manifest for component Citadel...
- Applying manifest for component Prometheus...
- Applying manifest for component Policy...
- Applying manifest for component Injector...
- Applying manifest for component Telemetry...
- Applying manifest for component Grafana...
✔ Finished applying manifest for component Prometheus.
✔ Finished applying manifest for component Citadel.
✔ Finished applying manifest for component Kiali.
✔ Finished applying manifest for component Tracing.
✔ Finished applying manifest for component Galley.
✔ Finished applying manifest for component Injector.
✔ Finished applying manifest for component Policy.
✔ Finished applying manifest for component Grafana.
✔ Finished applying manifest for component IngressGateway.
✔ Finished applying manifest for component EgressGateway.
✔ Finished applying manifest for component Pilot.
✔ Finished applying manifest for component Telemetry.


✔ Installation complete

kubectl config set-context $(kubectl config current-context) --namespace=istio-system
----

IMPORTANT: `istio-demo.yaml` enables policy enforcement by default which is required in some sections of the tutorial. Please refer to https://istio.io/docs/tasks/policy-enforcement/enabling-policy/ if you are not using this file.

Wait for Istio's components to be ready

[source,bash,subs="+macros,+attributes"]
----
$ kubectl get pods -w

NAME                                        READY     STATUS      RESTARTS   AGE
grafana-6b65874977-v92gw                  1/1     Running   0          99s
istio-citadel-7bcc69d486-lqhwh            1/1     Running   0          101s
istio-egressgateway-6b6f694c97-bcpj8      0/1     Running   0          102s
istio-galley-6cf8f58d7b-gg8pv             1/1     Running   0          100s
istio-ingressgateway-8c9c9c9f5-glvhm      0/1     Running   0          103s
istio-pilot-c6dbc54b9-trwjt               0/1     Running   0          101s
istio-policy-66c4cf95c5-wf5hn             1/1     Running   2          100s
istio-sidecar-injector-79ccdf54c4-6dpnr   1/1     Running   0          100s
istio-telemetry-7bf96cb54f-jksfw          1/1     Running   3          101s
istio-tracing-c66d67cd9-mqhjx             1/1     Running   0          102s
kiali-8559969566-phh2b                    1/1     Running   0          101s
prometheus-66c5887c86-lfx7p               1/1     Running   0          101s
----