= Deploy Microservices
include::_attributes.adoc[]

[#deploycustomer]
== Deploy customer

Make sure you are logged in

[source,bash,subs="+macros,+attributes"]
----
oc whoami
or
kubectl config current-context
----

and you have setup the project/namespace

[source,bash,subs="+macros,+attributes"]
----
oc new-project tutorial
or
kubectl create namespace tutorial
kubectl config set-context $(kubectl config current-context) --namespace=tutorial

oc adm policy add-scc-to-user privileged -z default -n tutorial
----

Then clone the git repository

[source,bash,subs="+macros,+attributes"]
----
git clone https://github.com/redhat-developer-demos/istio-tutorial
cd istio-tutorial
----

Start deploying the microservice projects, starting with customer

Make sure `istioctl` is in your `PATH`:

[source,bash,subs="+macros,+attributes"]
----
$ istioctl version
version.BuildInfo{Version:"1.1.9", GitRevision:"879413c25b871ae6fd0df82bea1605baf12cba2e", User:"root", Host:"161bf1f4-8ef6-11e9-887b-0a580a2c0403", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.8-4-g879413c"}
----

=== Deploy Customer 

NOTE: You will deploy docker images that were privously built. If you want to build customer visit: xref:2build-microservices.adoc#buildcustomer[Build Customer]

Now let's deploy the customer pod with its sidecar

[source,bash,subs="+macros,+attributes"]
----
oc apply -f <(istioctl kube-inject -f link:{github-repo}/{customer-repo}/kubernetes/Deployment.yml[{customer-repo}/kubernetes/Deployment.yml]) -n tutorial
oc create -f link:{github-repo}/{customer-repo}/kubernetes/Service.yml[{customer-repo}/kubernetes/Service.yml] -n tutorial

or

kubectl apply -f <(istioctl kube-inject -f link:{github-repo}/{customer-repo}/kubernetes/Deployment.yml[{customer-repo}/kubernetes/Deployment.yml]) -n tutorial
kubectl create -f link:{github-repo}/{customer-repo}/kubernetes/Service.yml[{customer-repo}/kubernetes/Service.yml] -n tutorial
----

=== Expose customer

Since the `customer` service is the one our users will interact with, let's add an OpenShift Route that exposes that endpoint.

[source,bash,subs="+macros,+attributes"]
----
oc create -f link:{github-repo}/{customer-repo}/kubernetes/Gateway.yml[{customer-repo}/kubernetes/Gateway.yml] -n tutorial
or
kubectl create -f link:{github-repo}/{customer-repo}/kubernetes/Gateway.yml[{customer-repo}/kubernetes/Gateway.yml] -n tutorial

oc get pods -w -n tutorial
or
kubectl get pods -w
----

IMPORTANT: If your pod fails with `ImagePullBackOff`, it's possible that your current terminal isn't using the proper Docker Environment. See link:#setup-environment[Setup environment].

Wait until the status is `Running` and there are `2/2` pods in the `Ready` column. To exit, press `Ctrl+C`

Then test the customer endpoint

[source,bash,subs="+macros,+attributes"]
----
curl istio-ingressgateway-istio-system.{appdomain}/{path}
----

You should see the following error because the services `preference` and `recommendation` are not yet deployed.

----
customer => UnknownHostException: preference
----

Also review the logs

[source,bash,subs="+macros,+attributes"]
----
stern $(kubectl get pods|grep customer|awk '{ print $1 }'|head -1) -c customer
or
stern "customer-\w" -c customer
----

You should see a stacktrace containing this cause:

[source,bash,subs="+macros,+attributes"]
----
customer-6fc99b7bfd-5st28 customer Caused by: java.net.UnknownHostException: preference
----

[#deploypreference]
== Deploy Preference

NOTE: You will deploy docker images that were privously built. If you want to build preference visit: xref:2build-microservices.adoc#buildpreference[Build Preference]

Now let's deploy the preference pod with its sidecar

[source,bash,subs="+macros,+attributes"]
----
oc apply -f <(istioctl kube-inject -f link:{github-repo}/{preference-repo}/kubernetes/Deployment.yml[{preference-repo}/kubernetes/Deployment.yml]) -n tutorial
oc create -f link:{github-repo}/{preference-repo}/kubernetes/Service.yml[{preference-repo}/kubernetes/Service.yml]

or

kubectl apply -f <(istioctl kube-inject -f link:{github-repo}/{preference-repo}/kubernetes/Deployment.yml[{preference-repo}/kubernetes/Deployment.yml]) -n tutorial
kubectl create -f link:{github-repo}/{preference-repo}/kubernetes/Service.yml[{preference-repo}/kubernetes/Service.yml]
----

=== Wait preference to be deployed

[source, bash]
----
oc get pods -w -n tutorial
or
kubectl get pods -w
----

Wait until the status is `Running` and there are `2/2` pods in the `Ready` column. To exit, press `Ctrl+C`

[source,bash,subs="+macros,+attributes"]
----
curl istio-ingressgateway-istio-system.{appdomain}/{path}
----

It will respond with an error since the service `recommendation` is not yet deployed.

NOTE: We could make this a bit more resilient in a future iteration of this tutorial

[source,bash,subs="+macros,+attributes"]
----
customer => Error: 503 - preference => UnknownHostException: recommendation
----

and check out the logs

[source,bash,subs="+macros,+attributes"]
----
stern $(kubectl get pods|grep preference|awk '{ print $1 }'|head -1) -c preference
or
stern "preference-\w" -c preference
----

You should see a stacktrace containing this cause:

[source,bash,subs="+macros,+attributes"]
----
preference-v1-898764bdb-hz7s6 preference Caused by: java.net.UnknownHostException: recommendation
----

[#deployrecommendation]
== Deploy Recommendation

NOTE: You will deploy docker images that were privously built. If you want to build recommendation visit: xref:2build-microservices.adoc#buildrecommendation[Build Recommendation]

Now let's deploy the recommendation pod with its sidecar

[source,bash,subs="+macros,+attributes"]
----
oc apply -f <(istioctl kube-inject -f link:{github-repo}/{recommendation-repo}/kubernetes/Deployment.yml[{recommendation-repo}/kubernetes/Deployment.yml]) -n tutorial
oc create -f link:{github-repo}/{recommendation-repo}/kubernetes/Service.yml[{recommendation-repo}/kubernetes/Service.yml] -n tutorial
oc get pods -w

or 

kubectl apply -f <(istioctl kube-inject -f link:{github-repo}/{recommendation-repo}/kubernetes/Deployment.yml[{recommendation-repo}/kubernetes/Deployment.yml]) -n tutorial
kubectl create -f link:{github-repo}/{recommendation-repo}/kubernetes/Service.yml[{recommendation-repo}/kubernetes/Service.yml]
kubectl get pods -w
----

=== Wait recommendation to be deployed

Wait until the status is `Running` and there are `2/2` pods in the `Ready` column. To exit, press `Ctrl+C`

[source,bash,subs="+macros,+attributes"]
----
curl istio-ingressgateway-istio-system.{appdomain}/{path}
----

it should now return

[source,bash,subs="+macros,+attributes"]
----
customer => preference => recommendation v1 from '99634814-sf4cl': 1
----

and you can monitor the `recommendation` logs with

[source,bash,subs="+macros,+attributes"]
----
stern $(kubectl get pods|grep recommendation-v1|awk '{ print $1 }'|head -1) -c recommendation
or
stern "recommendation-v1-\w" -c recommendation-v1
----


[#redeployingcode]
== Updating Redeploying Code

When you wish to change code (e.g. editing the .java files) and wish to "redeploy", simply:

[source,bash]
----
cd {servicename}/java/{quarkus|springboot|vertx}

vi src/main/java/com/redhat/developer/demos/{servicename}/{Servicename}{Controller|Verticle}.java
----

Make your changes, save it and then:

[source,bash]
----
mvn clean package
docker build -t example/{servicename}:v1 .

oc get pods -o jsonpath='{.items[*].metadata.name}' -l app={servicename}
oc get pods -o jsonpath='{.items[*].metadata.name}' -l app={servicename},version=v1
oc delete pod -l app={servicename},version=v1

or

kubectl get pods -o jsonpath='{.items[*].metadata.name}' -l app={servicename}
kubectl get pods -o jsonpath='{.items[*].metadata.name}' -l app={servicename},version=v1
kubectl delete pod -l app={servicename},version=v1
----

Why the delete pod?

Based on the Deployment configuration, Kubernetes/OpenShift will recreate the pod, based on the new docker image as it attempts to keep the desired replicas available

[source,bash]
----
oc describe deployment {servicename} | grep Replicas
or
kubectl describe deployment {servicename} | grep Replicas
----
