= Simple Route Rules
include::_attributes.adoc[]
:svc-version: v2

For this use case, we need to create a modified version of Recommendations

[#deployrecommendationv2]
== Create recommendation:v2

ifndef::workshop[]

We can experiment with Istio controlling traffic by making a change to `RecommendationVerticle.java` like the following and creating a "v2" docker image.

[#srr-update-recommendation-v2]
[source,java,subs="+macros,+attributes"]
----
private static final String RESPONSE_STRING_FORMAT = "recommendation v2 from '%s': %d\n";
----
copyToClipboard::srr-update-recommendation-v2[]

The "v2" tag during the Docker build is significant.

There is also a second `deployment.yml` file to label things correctly

=== Docker build (if you have access to Docker daemon)

[#srr-rebuild-recommendation-v2]
[source,bash,subs="+macros,+attributes"]
----
cd recommendation/java/quarkus && \
mvn clean package -DskipTests  && \
docker build -t example/recommendation:v2 .
docker images | grep recommendation
----
copyToClipboard::srr-rebuild-recommendation-v2[]

A successful build will show the following container images:

[source,bash,subs="+macros,+attributes"]
----
example/recommendation                  v2                  c31e399a9628        5 seconds ago       438MB
example/recommendation                  v1                  f072978d9cf6        8 minutes ago      438MB
----

IMPORTANT: We have a 2nd Deployment to manage the v2 version of recommendation. 

:svc-name: recommendation
:svc-repo: {recommendation-repo}
include::ROOT:partial$deploy-microservice.adoc[tag=deploy]

endif::workshop[]

ifdef::workshop[]
== Deploy Recommendation microservice V2 using an existing image

:svc-name: recommendation
:svc-repo: {recommendation-repo}
include::ROOT:partial$deploy-microservice.adoc[tag=deploy]

endif::workshop[]

Back to the main `istio-tutorial` directory

ifndef::workshop[]
[source,bash,subs="+macros,+attributes"]
----
cd ../../..
----
endif::workshop[]

=== Wait for v2 to be deployed

Wait for those pods to show "2/2", the istio-proxy/envoy sidecar is part of that pod

:doc-sec: recommendation-v2
include::ROOT:partial$command-snippets.adoc[tag=kgpow]

The get pods command show now list the pods as shown below:

[source,bash,subs="+macros,+attributes"]
----
NAME                                  READY     STATUS    RESTARTS   AGE
customer-3600192384-fpljb             2/2       Running   0          17m
preference-243057078-8c5hz           2/2       Running   0          15m
recommendation-v1-60483540-9snd9     2/2       Running   0          12m
recommendation-v2-2815683430-vpx4p   2/2       Running   0         15s
----

and test the customer endpoint

:doc-sec: recommendation-v2
include::ROOT:partial$command-snippets.adoc[tag=call-customer-svc]

you likely see "customer =&gt; preference =&gt; recommendation v1 from '99634814-d2z2t': 3", where '99634814-d2z2t' is the pod running v1 and the 3 is basically the number of times you hit the endpoint.

:doc-sec: recommendation-v2-v2
include::ROOT:partial$command-snippets.adoc[tag=call-customer-svc]
you likely see "customer =&gt; preference =&gt; recommendation v2 from '2819441432-5v22s': 1" as by default you get round-robin load-balancing when there is more than one Pod behind a Service

Send several requests to see their responses:

[#srr-several-requests]
[source, bash, subs="+macros,+attributes"]
----
./scripts/run.sh http://customer-tutorial{namespace-suffix}.{appdomain}
----
copyToClipboard::srr-several-requests[]

The default Kubernetes/OpenShift behavior is to round-robin load-balance across all available pods behind a single Service. Add another replica of recommendation-v2 Deployment.

:doc-sec: srr-scale-2
:deployment: recommendation-v2
:replicas: 2
include::ROOT:partial$command-snippets.adoc[tag=scale-deployment]

Now, you will see two requests into the v2 and one for v1.

[source,bash,subs="+macros,+attributes"]
----
customer => preference => recommendation v1 from '2819441432-qsp25': 29
customer => preference => recommendation v2 from '99634814-sf4cl': 37
customer => preference => recommendation v2 from '99634814-sf4cl': 38
----

Scale back to a single replica of the recommendation-v2 Deployment

:doc-sec: srr-scale-1
:deployment: recommendation-v2
:replicas: 1
include::ROOT:partial$command-snippets.adoc[tag=scale-deployment]

[#istiorouting]
== Changing Istio Routings

[#alltorecommendationv2]
=== All users to recommendation:v2

From the main istio-tutorial directory,

:doc-sec: recommendation-v2
:k8s-cmd-opt: create
:istio-file: destination-rule-recommendation-v1-v2.yml
include::ROOT:partial$command-snippets.adoc[tag=istio-rules]

:doc-sec: recommendation-v2 
:k8s-cmd-opt: create
:istio-file: virtual-service-recommendation-v2.yml
include::ROOT:partial$command-snippets.adoc[tag=istio-rules]

[#srr-run-many-requests]
[source,bash,subs="+macros,+attributes"]
----
./scripts/run.sh http://customer-tutorial{namespace-suffix}.{appdomain}
----
copyToClipboard::srr-run-many-requests[]

you should only see v2 being returned

[#alltorecommendationv1]
=== All users to recommendation:v1

Note: "replace" instead of "create" since we are overlaying the previous rule

:doc-sec: recommendation-all-v1
:k8s-cmd-opt: replace
:istio-file: virtual-service-recommendation-v1.yml
include::ROOT:partial$command-snippets.adoc[tag=istio-rules]

[#srr-get-vsvc]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n tutorial{namespace-suffix} get virtualservice 
----
copyToClipboard::srr-get-vsvc[]

[#srr-get-vsvc-yaml]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n tutorial{namespace-suffix} get virtualservice -o yaml 
----
copyToClipboard::srr-get-vsvc-yaml[]

[#alltorecommendationv1v2]
=== All users to recommendation v1 and v2

By simply removing the rule

:doc-sec: recommendation-v1-v2
:k8s-cmd-opt: delete
:istio-file: virtual-service-recommendation-v1.yml
include::ROOT:partial$command-snippets.adoc[tag=istio-rules]

and you should see the default behavior of load-balancing between v1 and v2

[#sarr-v1-v2-run-many]
[source,bash,subs="+macros,+attributes"]
----
./scripts/run.sh http://customer-tutorial{namespace-suffix}.{appdomain}
----
copyToClipboard::srr-v1-v2-run-many[]

[#canarydeploymentrecommendation]
=== Canary deployment: Split traffic between v1 and v2

Canary Deployment scenario: push v2 into the cluster but slowly send end-user traffic to it, if you continue to see success, continue shifting more traffic over time

:doc-sec: canary
:k8s-labels: app=recommendation
include::ROOT:partial$command-snippets.adoc[tag=kgpow]

[source,bash,subs="+macros,+attributes"]
----
NAME                                  READY     STATUS    RESTARTS   AGE
recommendation-v1-3719512284-7mlzw   2/2       Running   6          2h
recommendation-v2-2815683430-vn77w   2/2       Running   0          1h
----

Create the `virtualservice` that will send 90% of requests to v1 and 10% to v2

:doc-sec: canary-90-10
:k8s-cmd-opt: create
:istio-file: virtual-service-recommendation-v1_and_v2.yml
include::ROOT:partial$command-snippets.adoc[tag=istio-rules]

....
kubectl create -f link:{github-repo}/{istiofiles-dir}/virtual-service-recommendation-v1_and_v2.yml[istiofiles/virtual-service-recommendation-v1_and_v2.yml] -n tutorial{namespace-suffix}
....

and send in several requests:

[#srr-canary-recommendation-many]
[source, bash,subs="+macros,+attributes"]
----
./scripts/run.sh http://customer-tutorial{namespace-suffix}.{appdomain}
----
copyToClipboard::srr-canary-recommendation-many[]

In another terminal, change the mixture to be 75/25

:doc-sec: canary-75-25
:k8s-cmd-opt: create
:istio-file: virtual-service-recommendation-v1_and_v2_75_25.yml
include::ROOT:partial$command-snippets.adoc[tag=istio-rules]

....
kubectl replace -f link:{github-repo}/{istiofiles-dir}/virtual-service-recommendation-v1_and_v2_75_25.yml[istiofiles/virtual-service-recommendation-v1_and_v2_75_25.yml] -n tutorial{namespace-suffix}
....

Clean up

:doc-sec: srr-cleanup
:k8s-cmd-opt: delete
:istio-file: virtual-service-recommendation-v1_and_v2_75_25.yml
include::ROOT:partial$command-snippets.adoc[tag=istio-rules]

:doc-sec: srr-cleanup-1
:k8s-cmd-opt: delete
:istio-file: destination-rule-recommendation-v1-v2.yml
include::ROOT:partial$command-snippets.adoc[tag=istio-rules]

or you can run:

[#srr-script-cleanup]
[source, bash,subs="+macros,+attributes"]
----
pass:[$TUTORIAL_HOME]/scripts/clean.sh tutorial{namespace-suffix}
----
copyToClipboard::srr-script-cleanup[]
