= Advanced Route Rules
include::_attributes.adoc[]

[IMPORTANT]
.Before Start
====
You should have NO virtualservice nor destinationrule (in `tutorial` namespace) `istioctl get virtualservice` `istioctl get destinationrule` 
if so run:

[source, bash]
----
./scripts/clean.sh
----
====

[#canarydeploymentuseragent]
== Smart routing based on user-agent header (Canary Deployment)

What is your user-agent?

https://www.whoishostingthis.com/tools/user-agent/[https://www.whoishostingthis.com/tools/user-agent/]

Note: the "user-agent" header is added to OpenTracing baggage in the Customer service. From
there it is automatically propagated to all downstream services. To enable automatic
baggage propagation all intermediate services have to be instrumented with OpenTracing.
The baggage header for user agent has following form `baggage-user-agent: <value>`.

[#alltorecommendationv1]
=== Set recommendation to all v1

[source,bash,subs="+macros,+attributes"]
----
istioctl create -f link:{github-repo}/{istiofiles-dir}/destination-rule-recommendation-v1-v2.yml[istiofiles/destination-rule-recommendation-v1-v2.yml] -n tutorial
istioctl create -f link:{github-repo}/{istiofiles-dir}/virtual-service-recommendation-v1.yml[istiofiles/virtual-service-recommendation-v1.yml] -n tutorial
----

[#safaritov2]
=== Set Safari users to v2

[source,bash,subs="+macros,+attributes"]
----
istioctl replace -f link:{github-repo}/{istiofiles-dir}/virtual-service-safari-recommendation-v2.yml[istiofiles/virtual-service-safari-recommendation-v2.yml] -n tutorial

istioctl get virtualservice -n tutorial
----

and test with a Safari (or even Chrome on Mac since it includes Safari in the string). Safari only sees v2 responses from recommendation

and test with a Firefox browser, it should only see v1 responses from recommendation.

There are two ways to get the URL for your browser:

[source,bash]
----
minishift openshift service customer --in-browser
----

That will open the openshift service `customer` in browser

Or

if you need just the url alone:

[source,bash]
----
minishift openshift service customer --url
http://customer-tutorial.192.168.99.102.nip.io
----

You can also attempt to use the curl -A command to test with different user-agent strings. 

[source,bash]
----
curl -A Safari customer-tutorial.$(minishift ip).nip.io
curl -A Firefox customer-tutorial.$(minishift ip).nip.io
----

You can describe the virtualservice to see its configuration

[source,bash]
----
istioctl get virtualservice -o yaml -n tutorial
----

==== Remove the Safari rule

[source,bash]
----
istioctl delete -f istiofiles/virtual-service-safari-recommendation-v2.yml -n tutorial
----

[#mobiletov2]
=== Set mobile users to v2

[source,bash,subs="+macros,+attributes"]
----
istioctl create -f link:{github-repo}/{istiofiles-dir}/virtual-service-mobile-recommendation-v2.yml[istiofiles/virtual-service-mobile-recommendation-v2.yml] -n tutorial

curl -A "Mozilla/5.0 (iPhone; U; CPU iPhone OS 4(KHTML, like Gecko) Version/5.0.2 Mobile/8J2 Safari/6533.18.5" customer-tutorial.$(minishift ip).nip.io
----

==== Clean up

[source,bash]
----
istioctl delete -f istiofiles/destination-rule-recommendation-v1-v2.yml -n tutorial
istioctl delete -f istiofiles/virtual-service-mobile-recommendation-v2.yml -n tutorial
----

or you can run:

[source, bash]
----
./scripts/clean.sh
----

[#mirroringtraffic]
== Mirroring Traffic (Dark Launch)

[source,bash]
----
oc get pods -l app=recommendation -n tutorial
or 
kubectl get pods -l app=recommendation -n tutorial
----

You should have 2 pods for recommendation based on the steps above

[source,bash]
----
istioctl get virtualservice -n tutorial
istioctl get destinationrule
----

You should have NO virtualservice nor destinationrule (in `tutorial` namespace) `istioctl get virtualservice` `istioctl get destinationrule` 
if so run:

[source, bash]
----
./scripts/clean.sh
----

Make sure you are in the main directory of "istio-tutorial"

[source,bash,subs="+macros,+attributes"]
----
istioctl create -f link:{github-repo}/{istiofiles-dir}/destination-rule-recommendation-v1-v2.yml[istiofiles/destination-rule-recommendation-v1-v2.yml] -n tutorial
istioctl create -f link:{github-repo}/{istiofiles-dir}/virtual-service-recommendation-v1-mirror-v2.yml[istiofiles/virtual-service-recommendation-v1-mirror-v2.yml] -n tutorial

curl customer-tutorial.$(minishift ip).nip.io
----

Check the logs of recommendation-v2

[source,bash]
----
oc logs -f `oc get pods|grep recommendation-v2|awk '{ print $1 }'` -c recommendation
or
kubectl logs -f `oc get pods|grep recommendation-v2|awk '{ print $1 }'` -c recommendation
----

Clean up

[source,bash]
----
istioctl delete -f istiofiles/destination-rule-recommendation-v1-v2.yml -n tutorial
istioctl delete -f istiofiles/virtual-service-recommendation-v1-mirror-v2.yml -n tutorial
----

or you can run:

[source, bash]
----
./scripts/clean.sh
----

[#accesscontrol]
== Access Control

IMPORTANT: The Access Control rules take some time to be applied and reflected. Be patient here!

[#whitelist]
=== Whitelist

We'll create a whitelist on the preference service to only allow requests from the recommendation service, which will make the preference service invisible to the customer service. Requests from the customer service to the preference service will return a 404 Not Found HTTP error code.

[source,bash,subs="+macros,+attributes"]
----
istioctl create -f link:{github-repo}/{istiofiles-dir}/acl-whitelist.yml[istiofiles/acl-whitelist.yml] -n tutorial
----

[source,bash]
----
curl customer-tutorial.$(minishift ip).nip.io
customer => 404 NOT_FOUND:preferencewhitelist.listchecker.tutorial:customer is not whitelisted
----

==== Clean up

[source,bash]
----
istioctl delete -f istiofiles/acl-whitelist.yml -n tutorial
----

[#blacklist]
=== Blacklist

We'll create a blacklist making the customer service blacklist to the preference service. Requests from the customer service to the preference service will return a 403 Forbidden HTTP error code.

[source,bash,subs="+macros,+attributes"]
----
istioctl create -f link:{github-repo}/{istiofiles-dir}/acl-blacklist.yml[istiofiles/acl-blacklist.yml] -n tutorial
----

[source,bash]
----
curl customer-tutorial.$(minishift ip).nip.io
customer => 403 PERMISSION_DENIED:denycustomerhandler.denier.tutorial:Not allowed
----

==== Clean up

[source,bash]
----
istioctl delete -f istiofiles/acl-blacklist.yml -n tutorial
----

[#loadbalancer]
== Load Balancer

By default, you will see "round-robin" style load-balancing, but you can change it up, with the RANDOM option being fairly visible to the naked eye.

Add another v2 pod to the mix

[source,bash]
----
oc scale deployment recommendation-v2 --replicas=2 -n tutorial
or
kubectl scale deployment recommendation-v2 --replicas=2 -n tutorial
----

Wait a bit (oc get pods -w to watch)
and curl the customer endpoint many times

[source,bash]
----
curl customer-tutorial.$(minishift ip).nip.io
----

Add a 3rd v2 pod to the mix

[source,bash]
----
$ oc scale deployment recommendation-v2 --replicas=3 -n tutorial
$ oc get pods -n tutorial

or 

$ kubectl scale deployment recommendation-v2 --replicas=3 -n tutorial
$ kubectl get pods -n tutorial


NAME                                  READY     STATUS    RESTARTS   AGE
customer-1755156816-cjd2z             2/2       Running   0          1h
preference-3336288630-2cc6f          2/2       Running   0          1h
recommendation-v1-3719512284-bn42p   2/2       Running   0          59m
recommendation-v2-2815683430-97nnf   2/2       Running   0          43m
recommendation-v2-2815683430-d49n6   2/2       Running   0          51m
recommendation-v2-2815683430-tptf2   2/2       Running   0          33m
----

Wait for those 2/2 (two containers in each pod) and then poll the customer endpoint:

[source, bash]
----
./scripts/run.sh
----

The results should follow a fairly normal round-robin distribution pattern

[source,bash]
----
customer => preference => recommendation v1 from '99634814-d2z2t': 1145
customer => preference => recommendation v2 from '2819441432-525lh': 1
customer => preference => recommendation v2 from '2819441432-rg45q': 2
customer => preference => recommendation v2 from '2819441432-bs5ck': 181
customer => preference => recommendation v1 from '99634814-d2z2t': 1146
customer => preference => recommendation v2 from '2819441432-rg45q': 3
customer => preference => recommendation v2 from '2819441432-rg45q': 4
customer => preference => recommendation v2 from '2819441432-bs5ck': 182
----

Now, add the Random LB DestinationPolicy

[source,bash,subs="+macros,+attributes"]
----
istioctl create -f link:{github-repo}/{istiofiles-dir}/destination-rule-recommendation_lb_policy_app.yml[istiofiles/destination-rule-recommendation_lb_policy_app.yml] -n tutorial
----

And you should see a different pattern of which pod is being selected

[source,bash]
----
customer => preference => recommendation v2 from '2819441432-rg45q': 10
customer => preference => recommendation v2 from '2819441432-525lh': 3
customer => preference => recommendation v2 from '2819441432-rg45q': 11
customer => preference => recommendation v1 from '99634814-d2z2t': 1153
customer => preference => recommendation v1 from '99634814-d2z2t': 1154
customer => preference => recommendation v1 from '99634814-d2z2t': 1155
customer => preference => recommendation v2 from '2819441432-rg45q': 12
customer => preference => recommendation v2 from '2819441432-525lh': 4
customer => preference => recommendation v2 from '2819441432-525lh': 5
customer => preference => recommendation v2 from '2819441432-rg45q': 13
customer => preference => recommendation v2 from '2819441432-rg45q': 14
----

Clean up

[source,bash]
----
istioctl delete -f istiofiles/destination-rule-recommendation_lb_policy_app.yml -n tutorial

oc scale deployment recommendation-v2 --replicas=1 -n tutorial
or
kubectl scale deployment recommendation-v2 --replicas=1 -n tutorial
----

[#ratelimiting]
== Rate Limiting

IMPORTANT: The Rate Limiting rules take some time to be applied and reflected. Be patient here!

Here we will limit the number of concurrent requests into recommendation v2

Now apply the rate limit handler

[source,bash,subs="+macros,+attributes"]
----
istioctl create -f link:{github-repo}/{istiofiles-dir}/recommendation_rate_limit_handler.yml[istiofiles/recommendation_rate_limit_handler.yml]
----

Now setup the requestcount quota

[source,bash,subs="+macros,+attributes"]
----
istioctl create -f link:{github-repo}/{istiofiles-dir}/rate_limit_rule.yml[istiofiles/rate_limit_rule.yml]
----

Throw some requests at customer:

[source, bash]
----
./scripts/run.sh
----

You should see some 429 errors:

[source,bash]
----
customer => preference => recommendation v2 from '2819441432-f4ls5': 108
customer => preference => recommendation v1 from '99634814-d2z2t': 1932
customer => preference => recommendation v2 from '2819441432-f4ls5': 109
customer => preference => recommendation v1 from '99634814-d2z2t': 1933
customer => 503 preference => 429 RESOURCE_EXHAUSTED:Quota is exhausted for: RequestCount
customer => preference => recommendation v1 from '99634814-d2z2t': 1934
customer => preference => recommendation v2 from '2819441432-f4ls5': 110
customer => preference => recommendation v1 from '99634814-d2z2t': 1935
customer => 503 preference => 429 RESOURCE_EXHAUSTED:Quota is exhausted for: RequestCount
customer => preference => recommendation v1 from '99634814-d2z2t': 1936
customer => preference => recommendation v2 from '2819441432-f4ls5': 111
customer => preference => recommendation v1 from '99634814-d2z2t': 1937
customer => 503 preference => 429 RESOURCE_EXHAUSTED:Quota is exhausted for: RequestCount
customer => preference => recommendation v1 from '99634814-d2z2t': 1938
customer => preference => recommendation v2 from '2819441432-f4ls5': 112
----

Clean up

[source,bash]
----
istioctl delete -f istiofiles/rate_limit_rule.yml

istioctl delete -f istiofiles/recommendation_rate_limit_handler.yml
----

or you can run:

[source, bash]
----
./scripts/clean.sh
----