= Access Control List
include::_attributes.adoc[]

[IMPORTANT]
.Before Start
====
You should have NO virtualservice nor destinationrule (in `tutorial` namespace) `kubectl get virtualservice{namespace-suffix}` `kubectl get destinationrule{namespace-suffix}` 
if so run:

[source, bash]
----
./scripts/clean.sh
----
====

IMPORTANT: The Access Control rules take some time to be applied and reflected. Be patient here!

[#whitelist]
== Whitelist

We'll create a whitelist on the preference service to only allow requests from the recommendation service, which will make the preference service invisible to the customer service. Requests from the customer service to the preference service will return a 404 Not Found HTTP error code.

[source,bash,subs="+macros,+attributes"]
----
kubectl create -f link:{github-repo}/{istiofiles-dir}/acl-whitelist.yml[istiofiles/acl-whitelist.yml] -n tutorial
----

[source,bash,subs="+macros,+attributes"]
----
curl customer-tutorial.$(minishift ip).nip.io
customer => 404 customer => Error: 403 - PERMISSION_DENIED:preferencewhitelist.listchecker.tutorial:customer is not whitelisted
----

=== Clean up

[source,bash,subs="+macros,+attributes"]
----
kubectl delete -f istiofiles/acl-whitelist.yml -n tutorial
----

[#blacklist]
== Blacklist

We'll create a blacklist making the customer service blacklist to the preference service. Requests from the customer service to the preference service will return a 403 Forbidden HTTP error code.

[source,bash,subs="+macros,+attributes"]
----
kubectl create -f link:{github-repo}/{istiofiles-dir}/acl-blacklist.yml[istiofiles/acl-blacklist.yml] -n tutorial
----

[source,bash,subs="+macros,+attributes"]
----
curl customer-tutorial.$(minishift ip).nip.io
customer => Error: 403 - PERMISSION_DENIED:denycustomerhandler.denier.tutorial:Not allowed
----

=== Clean up

[source,bash,subs="+macros,+attributes"]
----
kubectl delete -f istiofiles/acl-blacklist.yml -n tutorial
----

