= Authorization Policy
include::_attributes.adoc[]

[IMPORTANT]
.Before Start
====
You should have NO virtualservice nor destinationrule (in `tutorial` namespace) `kubectl get virtualservice{namespace-suffix}` `kubectl get destinationrule{namespace-suffix}` 
if so run:

[.console-input]
[source, bash,subs="+macros,+attributes"]
----
./scripts/clean.sh tutorial{namespace-suffix}
----
====

[IMPORTANT]
====
This section requires mutual TLS enabled because the following examples use principal in the policies.
This is enabled by default, so you should not do anything special.
====

IMPORTANT: The Authorization Policy rules take some time to be applied and reflected. Be patient here!

[#authpolicies]
== Authorization Policies

We'll create an authorization path that will only allow the following communication path: customer -> preference -> recommendation.
Any other path will result to a 403 forbidden HTTP error.

=== Denny All

Let's start by denning any request that occurs on our application:

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl apply -f link:{github-repo}/{istiofiles-dir}/authorization-policy-deny-all.yaml[istiofiles/authorization-policy-deny-all.yaml] -n tutorial{namespace-suffix}
----

Then if you do:

include::curl.adoc[]

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
RBAC: access denied
----

Of course any interaction is forbidden.

=== Allow Customer

Let's permit the interaction to customer service:

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl apply -f link:{github-repo}/{istiofiles-dir}/authorization-policy-allow-customer.yaml[istiofiles/authorization-policy-allow-customer.yaml] -n tutorial{namespace-suffix}
----

Then if you do:

include::curl.adoc[]

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
customer => Error: 403 - RBAC: access denied
----

Now `customer` is reached but not preference.

=== Allow Preference

Let's permit it:

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl apply -f link:{github-repo}/{istiofiles-dir}/authorization-policy-allow-preference.yaml[istiofiles/authorization-policy-allow-preference.yaml] -n tutorial{namespace-suffix}
----

Then if you do:

include::curl.adoc[]

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
customer => Error: 503 - preference => Error: 403 - RBAC: access denied
----

The `preference` service is accessed but not the recommendation one.

=== Allow Recommendation

Let's end up by allowing all the path:

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl apply -f link:{github-repo}/{istiofiles-dir}/authorization-policy-allow-recommendation.yaml[istiofiles/authorization-policy-allow-recommendation.yaml] -n tutorial{namespace-suffix}
----

Then if you do:

include::curl.adoc[]

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
customer => preference => recommendation v1 from 'recommendation-v1-656788f945-9srp8': 12
----

=== Validate Other Paths

Now let's assume that someone gets access to `recommendation` service:

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl exec -it -n tutorial $(kubectl get pods -n tutorial|grep recommendation|awk '{ print $1 }'|head -1) -c recommendation /bin/bash
----

You will be inside the application container of `recommendation` pod. 
Now execute:

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
curl preference:8080
----

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
RBAC: access denied
----

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
exit
----

So you can see that `preference` service can only be accessed by `customer` service and not any other service such as `recommendation`.

=== Clean up

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
./scripts/clean.sh
----