= Mutual TLS and Istio
include::_attributes.adoc[]

[IMPORTANT]
.Before Start
====
You should have NO virtualservice, destinationrule, gateway or policy (in `tutorial` namespace) `kubectl get virtualservice{namespace-suffix}` `kubectl get destinationrule{namespace-suffix}` `kubectl get gateway{namespace-suffix}` `kubectl get policy{namespace-suffix}`
if so run:

[source, bash]
----
./scripts/clean.sh
----
====

In this chapter, we are going to see how to secure the communication between all services by enabling mutual _TLS_ in Istio.

[#testingtls]
== Testing mTLS

Depending on how you install Istio, you have mTLS enabled or not.
If you have followed this guide and installed the demo profile (xref:1setup.adoc[Setup]), then mTLS is not enabled.

To check if mTLS is enabled or not just run the next command:

[source, bash,subs="+macros,+attributes"]
----
istioctl authn tls-check $(kubectl get pods -n tutorial{namespace-suffix}|grep customer|awk '{ print $1 }'|head -1) customer.tutorial.svc.cluster.local

HOST:PORT                                    STATUS     SERVER         CLIENT     AUTHN POLICY     DESTINATION RULE
customer.tutorial.svc.cluster.local:8080     OK         PERMISSIVE     -          /default         -
----

If `CLIENT` is with `-` means that mTLS is not enabled.

To enable mTLS:

[source,bash,subs="+macros,+attributes"]
----
kubectl create -f link:{github-repo}/{istiofiles-dir}/authentication-enable-tls.yml[istiofiles/authentication-enable-tls.yml] -n tutorial{namespace-suffix}
kubectl create -f link:{github-repo}/{istiofiles-dir}/destination-rule-tls.yml[istiofiles/destination-rule-tls.yml] -n tutorial{namespace-suffix}
----

To check that mTLS is enabled run the next command:

[source, bash,subs="+macros,+attributes"
----
istioctl authn tls-check $(kubectl get pods -n tutorial{namespace-suffix}|grep customer|awk '{ print $1 }'|head -1) customer.tutorial.svc.cluster.local


HOST:PORT                                    STATUS     SERVER     CLIENT           AUTHN POLICY         DESTINATION RULE
customer.tutorial.svc.cluster.local:8080     OK         STRICT     ISTIO_MUTUAL     tutorial/default     tutorial/default
----

[#restore]
== Clean Up

[source,bash]
----
kubectl delete -f istiofiles/disable-mtls.yml
kubectl delete -f istiofiles/destination-rule-tls.yml
----

or you can run:

[source, bash]
----
./scripts/clean.sh
----
