= Java (Spring Boot, Vert.x and Microprofile) + Istio on Kubernetes/OpenShift

ifdef::workshop[]

[IMPORTANT]
.Before Start
====
- Ask an admin to link:http://bit.ly/OCPWorkshops[prepare the OpenShift instance].

- Adjust the documentation by modifying these link:https://github.com/redhat-developer-demos/istio-tutorial/blob/master/site-workshop.yml#L16-L18[three variables]


- Install of link:https://maistra.io/docs/getting_started/install/[Maistra 0.10] for Istio 1.1.7

- To update the nodes, follow the commands:
[source,bash]
----
ssh -i ocp-workshop.pem ec2-user@bastion......
sudo su -
for A in {1..<NUM_NODES>}; do ssh ec2-user@node$A.$(oc get nodes|grep master|perl -lne 'print $1 if /(...............internal)/') echo "vm.max_map_count = 262144" | sudo tee /etc/sysctl.d/99-elasticsearch.conf; sudo sysctl vm.max_map_count=262144; done
exit
----


- Make sure to use the following file as Control Plane configuration: 

[source,yaml]
----
include::workshop:example$istio-install.yaml[istio-install.yaml]
----

After the installation:

- Give users the capability to see istio-system
[source,bash,subs="+macros,+attributes"]
----
oc adm policy add-role-to-group view system:authenticated -n istio-system
----

- Give privileged access to containers

[source,bash,subs="+macros,+attributes"]
----
oc adm policy add-scc-to-group  privileged system:authenticated
----

- Remove weird resource limit

[source,bash,subs="+macros,+attributes"]
----
oc delete -n istio-system limitrange  istio-system-core-resource-limits
oc delete pods -n istio-system --all --grace-period=0 --force
----

====


endif::workshop[]

- A HTML version of this file is published at https://redhat-developer-demos.github.io/istio-tutorial/

- The source code is available at https://github.com/redhat-developer-demos/istio-tutorial

- Download the ebook "Introducing Istio Service Mesh for Microservices" for FREE at https://developers.redhat.com/books/introducing-istio-service-mesh-microservices/.

- If you are in a hurry and want to get hands-on with Istio insanely fast, just go to http://learn.openshift.com/servicemesh[http://learn.openshift.com/servicemesh] and start instantly.


There are three different and super simple microservices in this system and they are chained together in the following sequence:

```
customer → preference → recommendation
```

For now, they have a simple exception handling solution for dealing with a missing dependent service: it just returns the error message to the end-user.