#tag::kgpow[]
include::ROOT:partial$none.adoc[]
[tabs]
====
kubectl::
+
--
ifdef::k8s-labels[]
[#cmd-kgpow-{doc-sec}]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n tutorial{namespace-suffix} get pods -l {k8s-labels} -w
----
endif::[]
ifndef::k8s-labels[]
[#cmd-kgpow-{doc-sec}]
[source, bash,subs="+macros,+attributes"]
----
kubectl -n tutorial{namespace-suffix} get pods -w
----
endif::[]
copyToClipboard::cmd-kgpow-{doc-sec}[]
--
oc::
+
--
ifdef::k8s-labels[]
[#cmd-kgpow-{doc-sec}-oc]
[source, bash,subs="+macros,+attributes"]
----
oc -n tutorial{namespace-suffix} get pods -l {k8s-labels} -w
----
endif::[]
ifndef::k8s-labels[]
[#cmd-kgpow-{doc-sec}-oc]
[source, bash,subs="+macros,+attributes"]
----
oc -n tutorial{namespace-suffix} get pods -w
----
endif::[]
copyToClipboard::cmd-kgpow-{doc-sec}-oc[]
--
====
#end::kgpow[]

#tag::call-customer-svc[]
include::ROOT:partial$none.adoc[]
Wait until the status is `Running` and there are `2/2` pods in the `Ready` column. To exit, press kbd:[Ctrl+C]

[#invoke{doc-sec}-customer-endpoint]
[source,bash,subs="+macros,+attributes"]
----
curl http://customer-tutorial{namespace-suffix}.{appdomain}
----
copyToClipboard::invoke{doc-sec}-customer-endpoint[]

#end::call-customer-svc[]

#tag::istio-rules[]
include::ROOT:partial$none.adoc[]
[tabs]
=====
kubectl::
+
[#istio-rules-{doc-sec}-{istio-file}]
[source,bash,subs="attributes+,+macros"]
----
kubectl -n tutorial{namespace-suffix} {k8s-cmd-opt} -f link:{github-repo}/{istiofiles-dir}/{istio-file}[istiofiles/{istio-file}]
----
copyToClipboard::istio-rules-{doc-sec}-{istio-file}[]
oc::
+
--
[#istio-rules-oc-{doc-sec}-{istio-file}]
[source,bash,subs="attributes+,+macros"]
----
oc -n tutorial{namespace-suffix} {k8s-cmd-opt} -f link:{github-repo}/{istiofiles-dir}/{istio-file}[istiofiles/{istio-file}]
----
copyToClipboard::istio-rules-oc-{doc-sec}-{istio-file}[]
--
=====
#end::istio-rules[]

#tag::pod-ssh-exec[]
include::ROOT:partial$none.adoc[]
[tabs]
====
kubectl::
+
--
[#cb-{doc-sec}-{deployment}-trigger-misbehave]
[source,bash,subs="+macros,+attributes"]
----
kubectl exec -it -n tutorial{namespace-suffix} \
  $(kubectl get pods -n tutorial{namespace-suffix} \
  |grep {deployment}|awk '{ print $1 }'|head -1) -c recommendation /bin/bash
----
copyToClipboard::cb-{doc-sec}-{deployment}-trigger-misbehave[]
--
oc::
+
--
[#cb-oc-{doc-sec}-{deployment}-trigger-misbehave]
[source,bash,subs="+macros,+attributes"]
----
oc exec -it -n tutorial{namespace-suffix} \
 $(oc get pods -n tutorial{namespace-suffix} \
 |grep {deployment}|awk '{ print $1 }'|head -1) -c recommendation /bin/bash
----
copyToClipboard::cb-oc-{doc-sec}-{deployment}-trigger-misbehave[]
--
====
#end::pod-ssh-exec[]

#tag::scale-deployment[]
include::ROOT:partial$none.adoc[]
[tabs]
====
kubectl::
+
[#scale-{doc-sec}-{deployment}]
[source,bash,subs="+macros,+attributes"]
----
kubectl scale deployment {deployment} --replicas={replicas} -n tutorial{namespace-suffix}
----
copyToClipboard::scale-{doc-sec}-{deployment}[]
oc::
+
[#oc-scale-{doc-sec}-{deployment}]
[source,bash,subs="+macros,+attributes"]
----
oc scale deployment {deployment} --replicas={replicas} -n tutorial{namespace-suffix}
----
copyToClipboard::oc-scale-{doc-sec}-{deployment}[]
====
#end::scale-deployment[]