= Deploy Microservices
include::ROOT:page$_attributes.adoc[]


Create an environment variable for your user and log into OpenShift.

[source,bash,subs="+macros,+attributes"]
----
export WORKSHOP_USER=<your-username-number>

# Example:
# export WORKSHOP_USER=dev001

oc login -u $WORKSHOP_USER -p openshift {ocpurl}

# Note: the actual password will be provided by your instructor
----


[#deploycustomer]
== Deploy customer

Make sure you are logged in

[source,bash,subs="+macros,+attributes"]
----
oc whoami
or
kubectl config current-context
----

and you have setup the project/namespace

[source,bash,subs="+macros,+attributes"]
----
oc project $WORKSHOP_USER-istiotutorial
or
kubectl config set-context $(kubectl config current-context) --namespace=$WORKSHOP_USER-istiotutorial

ifndef::workshop[]
oc adm policy add-scc-to-user privileged -z default -n tutorial
endif::workshop[]
----

Then clone the git repository

[source,bash,subs="+macros,+attributes"]
----
git clone https://github.com/redhat-developer-demos/istio-tutorial
cd istio-tutorial
git checkout workshop/1.1.x

# verify you in the right branch
git branch -a
  master
* workshop/1.1.x
  remotes/origin/HEAD -> origin/master
  remotes/origin/book
  remotes/origin/book-1.0.4
  remotes/origin/gh-pages
  remotes/origin/k8s-builds
  remotes/origin/katacoda
  remotes/origin/master
  remotes/origin/recommendation-v2
  remotes/origin/workshop/1.1.x

----

Start deploying the microservice projects, starting with customer

=== Deploy Customer deploy using existing images

Let's deploy the customer pod with its sidecar

[source,bash,subs="+macros,+attributes"]
----
oc apply -f link:{github-repo}/{customer-repo}/kubernetes/Deployment.remote.yml[{customer-repo}/kubernetes/Deployment.remote.yml]
oc create -f link:{github-repo}/{customer-repo}/kubernetes/Service.yml[{customer-repo}/kubernetes/Service.yml]

or

kubectl apply -f link:{github-repo}/{customer-repo}/kubernetes/Deployment.remote.yml[{customer-repo}/kubernetes/Deployment.remote.yml]
kubectl create -f link:{github-repo}/{customer-repo}/kubernetes/Service.yml[{customer-repo}/kubernetes/Service.yml]

----

=== Expose customer

Since the `customer` service is the one our users will interact with, let's add an OpenShift Route that exposes that endpoint.

[source,bash,subs="+macros,+attributes"]
----
oc expose service customer 

oc get route 
oc get pods -w 

or

kubectl get route -o=jsonpath='{.items[0].spec.host}'
kubectl get pods -w
----

IMPORTANT: Wait until the status is `Running` and there are `2/2` pods in the `Ready` column. To exit, press `Ctrl+C`

Then test the customer endpoint

[source,bash,subs="+macros,+attributes"]
----
CUSTOMER_URL=$(oc get route/customer -o jsonpath="{.spec.host}")
curl $CUSTOMER_URL
----

You should see the following error because the services `preference` and `recommendation` are not yet deployed.

----
customer => Error: 503 - no healthy upstream
----

[#deploypreference]
== Deploy preference

=== Deploy Preference using existing image

[source,bash,subs="+macros,+attributes"]
----
oc apply -f link:{github-repo}/{preference-repo}/kubernetes/Deployment.remote.yml[{preference-repo}/kubernetes/Deployment.remote.yml]

oc create -f link:{github-repo}/{preference-repo}/kubernetes/Service.yml[{preference-repo}/kubernetes/Service.yml] 

or

kubectl apply -f link:{github-repo}/{preference-repo}/kubernetes/Deployment.remote.yml[{preference-repo}/kubernetes/Deployment.remote.yml]

kubectl create -f link:{github-repo}/{preference-repo}/kubernetes/Service.yml[{preference-repo}/kubernetes/Service.yml] 
----


=== Wait preference to be deployed

[source, bash,subs="+macros,+attributes"]
----
oc get pods -w 
or
kubectl get pods -w
----

Wait until the status is `Running` and there are `2/2` pods in the `Ready` column. To exit, press `Ctrl+C`

[source,bash,subs="+macros,+attributes"]
----
curl $CUSTOMER_URL
----

It will respond with an error since the service `recommendation` is not yet deployed.

NOTE: We could make this a bit more resilient in a future iteration of this tutorial

[source,bash,subs="+macros,+attributes"]
----
customer => Error: 503 - preference => Error: 503 - no healthy upstream
----

[#deployrecommendation]
== Deploy recommendation

=== Deploy Recommendation using existing images

[source,bash,subs="+macros,+attributes"]
----
oc apply -f link:{github-repo}/{recommendation-repo}/kubernetes/Deployment.remote.yml[{recommendation-repo}/kubernetes/Deployment.remote.yml]

oc create -f link:{github-repo}/{recommendation-repo}/kubernetes/Service.yml[{recommendation-repo}/kubernetes/Service.yml] 

oc get pods -w

or

kubectl apply -f link:{github-repo}/{recommendation-repo}/kubernetes/Deployment.remote.yml[{recommendation-repo}/kubernetes/Deployment.remote.yml]

kubectl create -f link:{github-repo}/{recommendation-repo}/kubernetes/Service.yml[{recommendation-repo}/kubernetes/Service.yml] 

kubectl get pods -w
----

=== Wait recommendation to be deployed

Wait until the status is `Running` and there are `2/2` pods in the `Ready` column. To exit, press `Ctrl+C`

[source,bash,subs="+macros,+attributes"]
----
curl $CUSTOMER_URL
----

it should now return

[source,bash,subs="+macros,+attributes"]
----
customer => preference => recommendation v1 from '5996759996-pnwvh': 1
----

