= Deploy Microservices
include::ROOT:page$_attributes.adoc[]


Create an environment variable for your user and log into OpenShift.

Set the workshop user e.g  `export WORKSHOP_USER=<your-username-number>`

[#workshop-set-env]
[source,bash,subs="+macros,+attributes"]
----
#Example:
export WORKSHOP_USER=1
oc login -u user$WORKSHOP_USER \
   openshift {ocpurl}
----
copyToClipboard::workshop-set-env[]


[#deploycustomer]
== Deploy customer

Make sure you are logged in

[tabs]
====
oc::
+
--
[#workshop-ocp-login]
[source,bash,subs="+macros,+attributes"]
----
oc whoami
----
copyToClipboard::workshop-ocp-login[]

Create workshop project 
[#workshop-set-project]
[source,bash,subs="+macros,+attributes"]
----
oc new-project tutorial{namespace-suffix}
----
copyToClipboard::workshop-set-project[]

ifndef::workshop[]
[#workshop-set-scc]
[source,bash,subs="+macros,+attributes"]
----
oc adm policy add-scc-to-user privileged -z default -n tutorial{namespace-suffix}
----
copyToClipboard::workshop-set-scc[]
endif::workshop[]
--
kubectl::
+
--
[#workshop-kubectl-login]
[source,bash,subs="+macros,+attributes"]
----
kubectl config current-context
----
copyToClipboard::workshop-kubectl-login[]

Create workshop namespace

[#workshop-set-ns]
[source,bash,subs="+macros,+attributes"]
----
kubectl create namespace tutorial{namespace-suffix} && \
kubectl config set-context $(kubectl config current-context) \
  --namespace=tutorial{namespace-suffix}
----
copyToClipboard::workshop-set-ns[]
[TIP]
=====
If you have installed https://github.com/ahmetb/kubectx[kubens], then you can change the namespace like:
[#workshop-set-kubens]
[source,bash,subs="+macros,+attributes"]
----
kubectl create namespace tutorial{namespace-suffix} && \
kubens tutorial{namespace-suffix} 
----
copyToClipboard::workshop-set-kubens[]
=====
--
====

Download the tutorial sources

[#workshop-download-sources]
[source,bash,subs="+macros,+attributes"]
----
git clone https://github.com/redhat-developer-demos/istio-tutorial && cd `basename $_`
----
copyToClipboard::workshop-download-sources[]

Start deploying the microservice projects, starting with customer

Make sure `istioctl` is in your `PATH` and it is of version `1.1.7`

[#workshop-check-istioctl]
[source,bash,subs="+macros,+attributes"]
----
$ istioctl version
----
copyToClipboard::workshop-check-istioctl[]

=== Deploy Customer deploy using existing images

:svc-name: customer
:svc-repo: {customer-repo}
include::ROOT:partial$deploy-microservice.adoc[tag=deploy]

=== Expose customer

Since the `customer` service is the one our users will interact with, let's add an OpenShift Route that exposes that endpoint.

[source,bash,subs="+macros,+attributes"]
----
oc expose service customer -n tutorial{namespace-suffix}

oc get route -n tutorial{namespace-suffix}
oc get pods -w -n tutorial{namespace-suffix}

or

kubectl get route -o=jsonpath='{.items[0].spec.host}'
kubectl get pods -w
----

IMPORTANT: If your pod fails with `ImagePullBackOff`, it's possible that your current terminal isn't using the proper Docker Environment. See link:#setup-environment[Setup environment].

Wait until the status is `Running` and there are `2/2` pods in the `Ready` column. To exit, press `Ctrl+C`

Then test the customer endpoint

[source,bash,subs="+macros,+attributes"]
----
curl http://customer-tutorial{namespace-suffix}.{appdomain}
----

You should see the following error because the services `preference` and `recommendation` are not yet deployed.

----
customer => UnknownHostException: preference
----


[#deploypreference]
== Deploy preference

=== Deploy Preference using existing image

:svc-name: preference
:svc-repo: {preference-repo}
include::ROOT:partial$deploy-microservice.adoc[tag=deploy]

=== Wait preference to be deployed

[source, bash,subs="+macros,+attributes"]
----
oc get pods -w -n tutorial{namespace-suffix}
or
kubectl get pods -w
----

Wait until the status is `Running` and there are `2/2` pods in the `Ready` column. To exit, press `Ctrl+C`

[source,bash,subs="+macros,+attributes"]
----
curl http://customer-tutorial{namespace-suffix}.{appdomain}
----

It will respond with an error since the service `recommendation` is not yet deployed.

NOTE: We could make this a bit more resilient in a future iteration of this tutorial

[source,bash,subs="+macros,+attributes"]
----
customer => Error: 503 - preference => UnknownHostException: recommendation
----

[#deployrecommendation]
== Deploy recommendation

=== Deploy Recommendation using existing images

:svc-name: recommendation
:svc-repo: {recommendation-repo}
include::ROOT:partial$deploy-microservice.adoc[tag=deploy]

=== Wait recommendation to be deployed

Wait until the status is `Running` and there are `2/2` pods in the `Ready` column. To exit, press `Ctrl+C`

[source,bash,subs="+macros,+attributes"]
----
curl http://customer-tutorial{namespace-suffix}.{appdomain}
----

it should now return

[source,bash,subs="+macros,+attributes"]
----
customer => preference => recommendation v1 from '99634814-sf4cl': 1
----

